version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 20
    commands:
      - echo "===== INSTALL PHASE ====="
      - echo "PWD BEFORE ANYTHING:"
      - pwd
      - echo "Listing root:"
      - ls -la .
      - echo "----- cd api/ClientApp -----"
      - cd api/ClientApp
      - echo "PWD after cd api/ClientApp:"
      - pwd
      - ls -la .
      - echo "----- npm install -----"
      - npm install
      - echo "PWD AFTER npm install:"
      - pwd
      - ls -la .
      - echo "----- cd ../.. -----"
      - cd ../..
      - echo "PWD after cd ../..:"
      - pwd
      - ls -la .

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      - echo "PWD at START of build phase:"
      - pwd
      - ls -la .
      - echo "----- cd api/ClientApp -----"
      - cd api/ClientApp
      - echo "PWD after cd api/ClientApp:"
      - pwd
      - ls -la .
      - echo "----- npm run build -----"
      - npm run build -- --configuration production
      - echo "PWD AFTER npm run build:"
      - pwd
      - ls -la .
      - echo "----- cd .. -----"
      - cd ..
      - echo "PWD after cd ..:"
      - pwd
      - ls -la .
      - echo "----- cd .. again to check behavior -----"
      - cd ..
      - echo "PWD after second cd ..:"
      - pwd
      - ls -la .

  post_build:
    commands:
      - echo "===== POST_BUILD PHASE ====="
      - echo "PWD in post_build:"
      - pwd
      - ls -la .
