version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 20
    commands:
      - echo "Installing Angular dependencies..."
      - cd api/ClientApp
      - npm install
      - cd ../..

  build:
    commands:
      - echo "Building Angular..."
      - cd api/ClientApp
      - npm run build -- --configuration production
      - cd ..

      - echo "Publishing .NET API..."
      - dotnet publish StargateAPI.csproj -c Release -o ./publish

      - echo "Copying Angular DIST to publish/wwwroot..."
      - mkdir -p publish/wwwroot
      - cp -r ClientApp/dist/ClientApp/* publish/wwwroot/

      - echo "Copying SQLite DB..."
      - cp starbase.db publish/

      - echo "Removing Angular source folder..."
      - rm -rf publish/ClientApp

      - cd ..

  post_build:
    commands:
      - echo "Creating deploy.zip..."
      - cd api/publish
      - zip -r ../../deploy.zip .
      - cd ../..
      - ls -R .

artifacts:
  files:
    - deploy.zip
