version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 20
    commands:
      - echo "Installing dependencies..."
      - cd api/ClientApp
      - npm install
      - cd ../..

  build:
    commands:
      - echo "Building Angular..."
      - cd api/ClientApp
      - npm run build -- --configuration production
      - cd ../..

      - echo "Publishing .NET API..."
      - cd api
      - dotnet publish -c Release -o publish
      - cd ..

      - echo "Copying Angular build output into API publish folder..."
      - mkdir -p api/publish/wwwroot
      - cp -R api/ClientApp/dist/ClientApp/* api/publish/wwwroot/

  post_build:
    commands:
      - echo "Creating deploy.zip..."
      - zip -r deploy.zip api/publish

artifacts:
  files:
    - deploy.zip
