version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 20
    commands:
      - echo "===== INSTALL PHASE ====="
      - echo "Using global.json:"
      - cat global.json || echo "No global.json found"

      - echo "Installing Angular dependencies..."
      - cd api/ClientApp
      - npm install
      - cd ../..

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      
      - echo "Building Angular..."
      - cd api/ClientApp
      - npm run build -- --configuration production
      - cd ../..

      - echo "Publishing .NET API..."
      - dotnet publish api/StargateAPI.csproj --configuration Release --runtime linux-x64 --self-contained false --output api/publish

      - echo "Copying Angular output to API wwwroot..."
      - rm -rf api/publish/ClientApp   
      - mkdir -p api/publish/wwwroot
      - cp -R api/ClientApp/dist/ClientApp/* api/publish/wwwroot/


artifacts:
  files:
    - api/publish/**/*
  discard-paths: no
