version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 20
    commands:
      - echo "===== INSTALL PHASE ====="
      - echo "Using global.json:"
      - cat global.json || echo "No global.json found"

      - echo "Installing Angular dependencies..."
      - cd api/ClientApp
      - npm install
      - cd ../..

  build:
    commands:
      - echo "===== BUILD PHASE ====="
      
      - echo "Building Angular..."
      - cd api/ClientApp
      - npm run build -- --configuration production
      - cd ../..

      - echo "Publishing .NET API..."
      - dotnet publish api/StargateAPI.csproj -c Release -o api/publish

      - echo "Copying Angular output to API wwwroot..."
      - mkdir -p api/publish/wwwroot
      - cp -R api/ClientApp/dist/ClientApp/* api/publish/wwwroot/

  post_build:
    commands:
      - echo "===== POST_BUILD ====="
      - zip -r deploy.zip api/publish

artifacts:
  files:
    - deploy.zip
