version: 0.2

phases:
  build:
    commands:
      - echo "Publishing StargateAPI for CodeDeploy..."
      - cd api
      - dotnet publish StargateAPI.csproj -c Release -o ../output

artifacts:
  files:
    - appspec.yml
    - scripts/**/*
    - output/**/*
