version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
      nodejs: 20
    commands:
      - echo "=== PRINTING DIRECTORY TREE ==="
      - ls -R .
      - echo "=== END DIRECTORY TREE ==="
      - echo "Installing Angular dependencies..."
      - cd api/ClientApp
      - npm install
      - cd ../..

  build:
    commands:
      - echo "Building Angular..."
      - cd api/ClientApp
      - npm run build -- --configuration production
      - cd ..

      - echo "Publishing .NET API..."
      - cd api
      - dotnet publish StargateAPI.csproj -c Release -o ./publish
      - cd ..

      - echo "Copying Angular DIST to publish/wwwroot..."
      - mkdir -p api/publish/wwwroot
      - cp -r api/ClientApp/dist/ClientApp/* api/publish/wwwroot/

      - echo "Copying SQLite DB..."
      - cp api/starbase.db api/publish/

      - echo "Cleaning ClientApp from publish folder..."
      - rm -rf api/publish/ClientApp

  post_build:
    commands:
      - echo "Creating deploy.zip..."
      - cd api/publish
      - zip -r ../../deploy.zip .
      - cd ../..
      - ls -R .

artifacts:
  files:
    - deploy.zip
